= Microservice 外部依赖

使用 Docker 搭建开发环境的外部依赖

== 组件

=== MySQL

通过在 `./docker/config/mysql/init.sql` 文件中增加相关 SQL 即可给不同的组件配置不同的数据库、账户和密码。

[source%nowrap,bash,{source_attr}]
----
$ mysql -h127.0.0.1 -uroot -p123456
----

TIP: 该构建上下文是当前目录。所以，在 `./docker/images/mysql.dockerfile` 中添加文件时，填写的是当前目录的相对路径。

=== NACOS

http://127.0.0.1:8848/nacos/

Nacos /nɑ:kəʊs/ 是 Dynamic Naming and Configuration Service的首字母简称，一个更易于构建云原生应用的动态服务发现、配置管理和服务管理平台。

. 在 `./docker/config/mysql/init.sql` 文件中增加初始化数据库、账户和密码的 SQL 语句。
. 添加数据库初始化脚本 `./docker/config/nacos/mysql-schema.sql` 到 `docker/images/mysql.dockerfile` 中。
. 添加必要的环境变量配置文件 `./docker/env/nacos.env`。

=== Prometheus

http://localhost:9090/

添加新的组件，需要在 `./docker/config/prometheus/prometheus.yml` 中增加任务配置。

=== Grafana

http://localhost:3000/ admin/admin

. 添加 Prometheus 类型的 Data Source，URL： http://prometheus:9090，请求方法： GET
. 添加监控面板，将 https://github.com/nacos-group/nacos-template/blob/master/nacos-grafana.json[模板] （本地目录： ./docker/config/grafana/provisioning/dashboards/nacos.json） 导入即可。
+
--
常用软件的 Grafana 监控面板可以在 https://grafana.com/grafana/dashboards/[Grafana dashboards^] 页面搜索，选择合适的面板，下载 JSON 导入即可。
--

=== Elasticsearch

由于 Elasticsearch 8+ 的版本修改了安全策略，不允许 Kibana 使用超级管理员 `elastic` 连接 Elasticsearch，这里选用 7.x 版本做演示。

还有一点需要提醒，在设置 Elasticsearch 的超级管理员 `elastic` 的账户密码时，如果密码是全部的阿拉伯数字，那么需要用双引号或者单引号括起来。

在测试中，还遇到一个磁盘过载导致的只读问题。解决方式如下：

. `curl -X GET "localhost:9200/_cat/allocation?v&pretty"` 查看磁盘使用情况
. 解除只读状态
+
--
[source%nowrap,bash,{source_attr}]
----
$ curl -X PUT "localhost:9200/test/_settings" -H 'Content-Type: application/json' -d'
{
  "index.blocks.read_only_allow_delete": null
}
'
----
--
+
. 调整磁盘使用阈值
+
--
[source%nowrap,bash,{source_attr}]
----
$ curl -X PUT "localhost:9200/_cluster/settings" -H 'Content-Type: application/json' -d'
{
  "persistent": {
    "cluster.routing.allocation.disk.watermark.flood_stage": "97%", <1>
    "cluster.routing.allocation.disk.watermark.high": "90%", <2>
    "cluster.routing.allocation.disk.watermark.low": "85%",  <3>
    "cluster.info.update.interval": "1m" <4>
  }
}
'
----
<1> 当磁盘使用超过这个百分比时，索引会被设置为只读。
<2> 当磁盘使用超过这个百分比时，Elasticsearch 会尝试将分片迁移到磁盘使用较少的节点。
<3> 当磁盘使用超过这个百分比时，会触发分片的重新分配。
<4> 更新磁盘使用信息的间隔时间。
--

=== Kibana

http://localhost:5601

配置好 Elasticsearch 的网址、账户、密码就可以启动访问了。

在网上见到别人把 Kibana 整的很精美的监控图表，不知道是怎么搞的？回头再研究研究。

=== Fluentd

安装 Fluentd，通过 Fluentd 把 NACOS 和业务应用的日志传输到 Elasticsearch。目前先把 NACOS 的日志接入到 Elasticsearch。

接入成功后，`curl http://localhost:9200/nacos*/_search?pretty` 验证 NACOS 日志接入到 Elasticsearch。

下面重点介绍一下遇到的几个问题：

==== 插件缺失导致的启动失败

由于需求将日志输送到 Elasticsearch，这就需要 fluent-plugin-elasticsearch 插件。容器中，默认是没有安装的，启动时就会导致失败。

两种解决办法：

. 使用类似 MySQL 的办法，基于官方镜像，在里面装上插件，再打包一个新镜像。
. 在 `docker-compose.yml` 中通过 `command` 指令，运行 Fluentd 时安装 fluent-plugin-elasticsearch 插件。

为了简单起见，直接选择第二种方案。安装命令是： `command: ["sh", "-c", "gem install fluent-plugin-elasticsearch --no-document && fluentd -c /fluentd/etc/fluent.conf"]`。

==== 由于权限导致的安装失败

配置上述命令后，启动就遇到了该错误： `ERROR:  While executing gem ... (Gem::FilePermissionError)  You don't have write permissions for the /usr/lib/ruby/gems/3.2.0 directory.`。

这是由于默认以 `fluent` 运行的，该用户对 `/usr/lib/ruby/gems/3.2.0` 没有写权限。所以，在安装插件时，就会报错。

解决方案： 通过在 `docker-compose.yml` 中增加 `user: root` 配置，使用 `root` 来运行容器。

==== 健康检查

尝试了三种方案：

. 启用 `monitor_agent` 插件，监控 `9880` 端口。失败！
. 使用 `nc` 检查 Fluentd 监听的 `24224` 端口。失败！
. 最后通过使用 `test: [ "CMD-SHELL", "pgrep fluentd || exit 1" ]` 来查看 Fluentd 的进程方式。成功！

== Jaeger

http://localhost:16686

最新版的 Jaeger 都被集成到了 `jaegertracing/all-in-one` 这个一个镜像中。简化了很多配置。

初次使用 Jaeger，肯定会惊讶于它居然需要这么多端口号，具体端口号的解释见： https://www.jaegertracing.io/docs/1.62/getting-started/[Jaeger Getting Started^]。

== OpenTelemetry

OpenTelemetry 并不需要在 Docker 中启动或者配置什么。在目前的架构中，Jaeger 是作为 OpenTelemetry 的一个实现来出现的。 OpenTelemetry 需要做的就是下载一个 Java Agent，执行 `docker/config/opentelemetry/download-opentelemetry-agent.sh` 脚本即可下载最新版的 Java Agent。在业务应用启动时，增加如下 JVM 参数：

[source%nowrap,{source_attr}]
----
-javaagent:/path/to/opentelemetry-javaagent.jar
-Dotel.service.name=<业务系统名称>
-Dotel.traces.exporter=otlp <1>
-Dotel.exporter.otlp.endpoint="http://localhost:4318" <2>
-Dotel.exporter.otlp.protocol=http/protobuf <3>
-Dotel.logs.exporter=console  <4>
-Dotel.metrics.exporter=prometheus <5>
-Dotel.exporter.prometheus.port=8079 <6>
-Dotel.metric.export.interval=1000 <7>
----
<1> 选择 `otlp` exporter
<2> `otlp` exporter 的网址
<3> 传输协议。这个必须和 `otel.exporter.otlp.endpoint` 配置项及 Jaeger 暴露的端口相对应，否则传输失败。
<4> 将日志输出到控制台。
<5> 将 Metrics 信息导出到 Prometheus
<6> Metrics 导出的端口。Prometheus 会从端口号拉去，路径是 `/metrics`。
<7> Metrics 统计间隔。

应用启动后，可以在 Prometheus 的配置文件 `docker/config/prometheus/prometheus.yml` 中增加相关配置：

[source%nowrap,yaml,{source_attr}]
----
  # 业务系统：商城
  - job_name: 'mall-system'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8099'] <1>
----
<1> 从 Docker 容器访问主机端口，使用 `host.docker.internal`。

这样就会拉去业务系统的监控信息，可以在 http://localhost:9090/targets 页面看到系统的运行状况。

详细配置见： https://opentelemetry.io/docs/languages/java/configuration/[OpenTelemetry Configure the SDK^]。

== 常用命令

. `docker exec -it nacos /bin/bash`

== 参考资料

. https://github.com/nacos-group/nacos-docker/tree/master[nacos-group/nacos-docker^] -- example/standalone-mysql-5.7.yaml
. https://dev.mysql.com/doc/refman/8.4/en/charset-mysql.html[Character Sets and Collations in MySQL 8.4^]
. https://www.cnblogs.com/sparkdev/p/9573248.html[Dockerfile 中的 COPY 与 ADD 命令^]
. https://blog.csdn.net/wmq880204/article/details/80591096[创建MySQL用户 赋予某指定库表的权限_grant all privileges on 指定表权限^]
. https://blog.csdn.net/u014796999/article/details/53559747[mysql刷新权限命令_sql给guest用户设置查询、更新权限^]
. https://nacos.io/en-us/docs/v2/guide/admin/monitor-guide.html[Nacos monitor guide^]
. https://blog.csdn.net/qq_32605245/article/details/134545714[最全docker之docker-compose.yml详解_docker-compose.yml^]
. https://www.cnblogs.com/johnnyzen/p/17785405.html[Docker Compose 基础教程（概念/基础操作）^]



